fix: (8) changed parens and checked IP Address

diff --git a/.github/workflows/build_deploy_rcb_fe.yml b/.github/workflows/build_deploy_rcb_fe.yml
--- a/.github/workflows/build_deploy_rcb_fe.yml
+++ b/.github/workflows/build_deploy_rcb_fe.yml
@@ -68,12 +68,17 @@ jobs:
 
         - name: Fetch server public IP address
           run: |
-            export $IP_ADDRESS=${az network public-ip show \
+            export $IP_ADDRESS=$(az network public-ip show \
               --resource-group apprenticeship-2024-rg \
               --name rcb-public-ip \
               --query "ipAddress" \
-              --output tsv 2> nul}
-            echo IP_ADDRESS=$IP_ADDRESS > $GITHUB_ENV
+              --output tsv 2> nul)
+            if [ $IP_ADDRESS = '' ]; then
+              echo "IP Address not found! Check the infrastructure workflow and apply the changes and try again."
+              exit 1
+            else
+              echo IP_ADDRESS=$IP_ADDRESS > $GITHUB_ENV
+            fi
         
         - name: Print IP address
           run: echo $IP_ADDRESS
